[workspace]
resolver = "3"
members = ["mimir", "mimir-api-types", "mimir-client", "mimir-core", "mimir-server"]
default-members = ["mimir"]

[workspace.package]
version = "0.19.3"
authors = ["BhavsarDevansh"]
license = "GPL-3.0"
description = "A persistent personal intelligence that learns from your life"
repository = "https://github.com/BhavsarDevansh/Mimir"
homepage = "https://github.com/BhavsarDevansh/Mimir"
edition = "2024"
rust-version = "1.85"
