ALTER TABLE fact_dependencies ADD COLUMN is_positive BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE facts ADD COLUMN inference_depth INTEGER NOT NULL DEFAULT 0;
ALTER TABLE facts ADD COLUMN stale_confidence BOOLEAN NOT NULL DEFAULT FALSE;
