#!/usr/bin/env bash
set -euo pipefail

# Regression guard for the release helper (scripts/new-release.sh): version
# detection, local/remote tag checks, release-notes source selection
# (GitHub-generated by default, `RELEASE_NOTES_FILE` override), working-tree
# and `gh` validation, resumable publication, and the dry-run paths must
# behave deterministically so a release never publishes with the wrong tag,
# body, or version.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

source "$SCRIPT_DIR/new-release.sh"

fail() { printf 'FAIL: %s\n' "$*" >&2; exit 1; }

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

cat > "$TMP/Cargo.toml" <<'EOF'
[workspace.package]
version = "9.9.9"
EOF

# detect_version reads the workspace package version.
got="$(detect_version "$TMP/Cargo.toml")"
[[ "$got" == "9.9.9" ]] || fail "detect_version returned '$got', want 9.9.9"

# tag_exists reflects local tags in the given repository.
REPO="$TMP/repo"
git init -q "$REPO"
git -C "$REPO" config user.email test@example.com
git -C "$REPO" config user.name Test
git -C "$REPO" commit -q --allow-empty -m init
tag_exists "$REPO" 9.9.9 && fail "tag_exists reported a missing tag as present"
git -C "$REPO" tag v9.9.9
tag_exists "$REPO" 9.9.9 || fail "tag_exists reported an existing tag as missing"

# remote_tag_target reflects origin tags: the peeled commit for annotated
# tags, the raw commit for lightweight tags, and nothing when origin has none.
BARE="$TMP/remote-origin.git"
git init -q --bare "$BARE"
git -C "$REPO" remote add origin "$BARE"
[[ -z "$(remote_tag_target "$REPO" v9.9.7)" ]] || \
    fail "remote_tag_target reported a missing remote tag as present"
git -C "$REPO" push -q origin v9.9.9
[[ "$(remote_tag_target "$REPO" v9.9.9)" == "$(git -C "$REPO" rev-parse HEAD)" ]] || \
    fail "remote_tag_target missed the lightweight tag"
git -C "$REPO" tag -a v9.9.8 -m "Release 9.9.8"
git -C "$REPO" push -q origin v9.9.8
[[ "$(remote_tag_target "$REPO" v9.9.8)" == "$(git -C "$REPO" rev-parse "refs/tags/v9.9.8^{}")" ]] || \
    fail "remote_tag_target missed the annotated tag"
git -C "$REPO" remote remove origin

# Sandbox fixture: a hermetic copy of the release script plus a bare origin,
# so main() runs against a throwaway repository.
make_sandbox() {
    local sandbox="$1" origin="$2"
    mkdir -p "$sandbox/scripts"
    cp "$SCRIPT_DIR/new-release.sh" "$sandbox/scripts/new-release.sh"
    chmod +x "$sandbox/scripts/new-release.sh"
    cp "$TMP/Cargo.toml" "$sandbox/Cargo.toml"
    git init -q "$sandbox"
    git -C "$sandbox" config user.email test@example.com
    git -C "$sandbox" config user.name Test
    git -C "$sandbox" commit -q --allow-empty -m init
    git -C "$sandbox" branch -M main
    git init -q --bare "$origin"
    git -C "$sandbox" remote add origin "$origin"
    git -C "$sandbox" add -A
    git -C "$sandbox" commit -q -m fixtures
    git -C "$sandbox" push -q origin main
}

# gh test double: never touches the real GitHub CLI. `release view` reports a
# missing release, `release create` fails once (simulating a transient
# publication failure) before succeeding (tracked via GH_STATE_FILE), and every
# create invocation appends its arguments to GH_ARGS_FILE for assertions.
GH_SHIM="$TMP/gh-shim"
mkdir -p "$GH_SHIM"
cat > "$GH_SHIM/gh" <<'EOF'
#!/usr/bin/env bash
STATE_FILE="${GH_STATE_FILE:-/nonexistent-gh-state}"
ARGS_FILE="${GH_ARGS_FILE:-/dev/null}"
case "$1" in
    auth)
        exit 0
        ;;
    release)
        case "$2" in
            view)
                exit 1
                ;;
            create)
                printf '%s\n' "$*" >> "$ARGS_FILE"
                if [[ ! -f "$STATE_FILE" ]]; then
                    touch "$STATE_FILE"
                    echo "simulated publication failure" >&2
                    exit 1
                fi
                echo "https://example.com/releases/$3"
                ;;
        esac
        ;;
esac
exit 0
EOF
chmod +x "$GH_SHIM/gh"
export PATH="$GH_SHIM:$PATH"
GH_ARGS_FILE="$TMP/gh-args"
export GH_ARGS_FILE

# A tag already on origin at a different commit aborts before any local tag
# is created or GitHub is touched.
SANDBOX="$TMP/sandbox-remote"
make_sandbox "$SANDBOX" "$TMP/origin-remote.git"
git -C "$SANDBOX" tag v9.9.9
git -C "$SANDBOX" push -q origin v9.9.9
git -C "$SANDBOX" tag -d v9.9.9
git -C "$SANDBOX" commit -q --allow-empty -m newer
out="$("$SANDBOX/scripts/new-release.sh" --version 9.9.9 2>&1)" && \
    fail "release must refuse when origin already has the tag at another commit"
[[ "$out" == *"Origin already has tag"* ]] || fail "remote-tag conflict lacks a clear message: $out"
tag_exists "$SANDBOX" 9.9.9 && fail "conflicting release created a local tag"

# A dirty working tree fails a real release but only warns under --dry-run.
SANDBOX="$TMP/sandbox-dirty"
make_sandbox "$SANDBOX" "$TMP/origin-dirty.git"
echo dirty > "$SANDBOX/uncommitted.txt"
out="$("$SANDBOX/scripts/new-release.sh" --version 9.9.9 2>&1)" && \
    fail "real release must refuse a dirty working tree"
[[ "$out" == *"Working tree is not clean"* ]] || fail "dirty-tree error lacks a clear message: $out"
tag_exists "$SANDBOX" 9.9.9 && fail "dirty-tree release created a tag"
out="$("$SANDBOX/scripts/new-release.sh" --dry-run --version 9.9.9 2>&1)" || \
    fail "dry run must tolerate a dirty working tree"
[[ "$out" == *"Working tree is not clean"* ]] || fail "dry run must warn about a dirty working tree"

# An unauthenticated gh aborts before the tag is created.
SANDBOX="$TMP/sandbox-noauth"
make_sandbox "$SANDBOX" "$TMP/origin-noauth.git"
NOAUTH_SHIM="$TMP/gh-noauth-shim"
mkdir -p "$NOAUTH_SHIM"
cat > "$NOAUTH_SHIM/gh" <<'EOF'
#!/usr/bin/env bash
echo "gh: not authenticated" >&2
exit 1
EOF
chmod +x "$NOAUTH_SHIM/gh"
out="$(PATH="$NOAUTH_SHIM:$PATH" "$SANDBOX/scripts/new-release.sh" --version 9.9.9 2>&1)" && \
    fail "real release must refuse an unauthenticated gh"
[[ "$out" == *"Not authenticated"* ]] || fail "auth failure lacks a clear message: $out"
tag_exists "$SANDBOX" 9.9.9 && fail "release tagged before checking gh authentication"

# A failed `gh release create` leaves the tag published; the next invocation
# resumes and creates the missing release instead of aborting.
SANDBOX="$TMP/sandbox-resume"
make_sandbox "$SANDBOX" "$TMP/origin-resume.git"
out="$(GH_STATE_FILE="$TMP/gh-state" "$SANDBOX/scripts/new-release.sh" --version 9.9.9 2>&1)" && \
    fail "first publication must fail when gh release create fails"
tag_exists "$SANDBOX" 9.9.9 || fail "failed publication must keep the local tag"
[[ -n "$(git -C "$SANDBOX" ls-remote origin refs/tags/v9.9.9)" ]] || \
    fail "failed publication must keep the pushed remote tag"
out="$(GH_STATE_FILE="$TMP/gh-state" "$SANDBOX/scripts/new-release.sh" --version 9.9.9 2>&1)" || \
    fail "resume run must publish the missing release"
[[ "$out" == *"Released: https://example.com/releases/v9.9.9"* ]] || \
    fail "resume run did not create the release: $out"
[[ "$(cat "$GH_ARGS_FILE")" == *"--generate-notes"* ]] || \
    fail "release create must pass --generate-notes by default"

# A RELEASE_NOTES_FILE that does not exist aborts (real run and dry run)
# before any tag is created.
SANDBOX="$TMP/sandbox-missing-notes"
make_sandbox "$SANDBOX" "$TMP/origin-missing-notes.git"
out="$(RELEASE_NOTES_FILE="$TMP/missing-notes.md" "$SANDBOX/scripts/new-release.sh" --version 9.9.9 2>&1)" && \
    fail "release must fail when RELEASE_NOTES_FILE is missing"
[[ "$out" == *"Release notes file not found"* ]] || fail "missing-notes error lacks a clear message: $out"
tag_exists "$SANDBOX" 9.9.9 && fail "missing RELEASE_NOTES_FILE still created a tag"
if RELEASE_NOTES_FILE="$TMP/missing-notes.md" "$SANDBOX/scripts/new-release.sh" --dry-run --version 9.9.9 >/dev/null 2>&1; then
    fail "dry run must fail when RELEASE_NOTES_FILE is missing"
fi

# A RELEASE_NOTES_FILE override publishes exactly those notes.
SANDBOX="$TMP/sandbox-notes-file"
make_sandbox "$SANDBOX" "$TMP/origin-notes-file.git"
printf 'hand-written release notes\n' > "$TMP/release-notes.md"
touch "$TMP/gh-state-notes"
out="$(GH_STATE_FILE="$TMP/gh-state-notes" RELEASE_NOTES_FILE="$TMP/release-notes.md" \
    "$SANDBOX/scripts/new-release.sh" --version 9.9.9 2>&1)" || \
    fail "release with a RELEASE_NOTES_FILE must succeed: $out"
[[ "$(cat "$GH_ARGS_FILE")" == *"--notes-file $TMP/release-notes.md"* ]] || \
    fail "release create must pass --notes-file for RELEASE_NOTES_FILE"

# Dry run rejects malformed versions.
if CARGO_MANIFEST="$TMP/Cargo.toml" \
    "$PROJECT_ROOT/scripts/new-release.sh" --dry-run --version abc >/dev/null 2>&1; then
    fail "dry run accepted a malformed version"
fi

# Dry run rejects duplicate version arguments.
if CARGO_MANIFEST="$TMP/Cargo.toml" \
    "$PROJECT_ROOT/scripts/new-release.sh" --dry-run --version 9.9.9 9.9.9 >/dev/null 2>&1; then
    fail "dry run accepted duplicate version arguments"
fi

# Dry run prints the plan and does not create the tag.
out="$(CARGO_MANIFEST="$TMP/Cargo.toml" \
    "$PROJECT_ROOT/scripts/new-release.sh" --dry-run --version 9.9.9 2>&1)"
[[ "$out" == *"9.9.9"* ]] || fail "dry run output does not mention the version"
[[ "$out" == *"Dry run"* ]] || fail "dry run output does not say it is a dry run"
[[ "$out" == *"GitHub-generated"* ]] || fail "dry run output does not mention the notes source"
tag_exists "$PROJECT_ROOT" 9.9.9 && fail "dry run created a tag"

printf 'new-release_test.sh: all checks passed\n'
