[package]
name = "mimir"
version = "0.7.1"
edition = "2024"

[dependencies]
mimir-server = { path = "../mimir-server" }
mimir-core = { path = "../mimir-core" }
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
dirs = "6.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
